swagger: '2.0'
info:
  title: Todo List API
  description: Create your own Todo list compatible apps
  version: 0.1.0
host: todo-grad-project-steve.herokuapp.com
consumes:
  - application/json
produces:
  - application/json
paths:
  /api/todo:
    get:
      summary: Todo List
      description: |
        A GET on the Todo endpoint returns a list of all stored items
        in the server's todo list. The response is an array of todos in
        JSON format, sorted by ID ascending.
      responses:
        200:
          description: An array of todos
          schema:
            type: array
            items:
              $ref: '#/definitions/Todo'
    post:
      summary: Add Todo
      description: |
        A POST on the Todo endpoint adds a new item to the server's
        Todo list. The request body should be a Todo with empty 'ID'
        and 'isComplete' fields.
      parameters:
        - in: body
          name: body
          description: |
            Todo item to be added to the Todo list, sans 'ID' and
            'isComplete' fields
          required: true
          schema:
            $ref: '#/definitions/Todo'
      responses:
        201:
          description: Successful operation
  /api/todo/{id}:
    put:
      summary: Edit Todo
      description: |
        Edits the state of the todo item with the given ID. The request body
        should be a todo item with an ID matching the path ID, which the
        corresponding todo on the server will be updated to match.
      parameters:
        - in: path
          name: id
          description: ID of todo that needs to be updated
          required: true
          type: integer
          format: int64
        - in: body
          name: body
          description: |
            Todo object with an ID matching the path, which the existing Todo
            in the server will be updated to match.
          required: true
          schema:
            $ref: '#/definitions/Todo'
      responses:
        201:
          description: Successful operation
        404:
          description: No Todo with the given ID exists in the server Todo list
        500:
          description: Sent Todo object's ID does not match the path ID
    delete:
      summary: Delete Todo
      description: |
        Deletes the todo item with the given ID.
      parameters:
        - in: path
          name: id
          description: ID of todo that needs to be deleted
          required: true
          type: integer
          format: int64
      responses:
        201:
          description: Successful operation
        404:
          description: No Todo with the given ID exists in the server Todo list
definitions:
  Todo:
    type: object
    properties:
      id:
        type: integer
        format: int64
      title:
        type: string
      isComplete:
        type: boolean
